# services:
#   redis:
#     image: redis
#     ports:
#       - 6379:6379
# pool:
#   vmImage: 'Ubuntu 16.04'

# variables:
#   imageName: 'aelf-sdk.java:$(build.buildId)'

# steps:
#   - script: cd scripts/aelf-node && bash start.sh
#   - script: docker build -f Dockerfile -t $(imageName) .
#     displayName: 'docker build'
jobs:
# All tasks on Linux
- job: build_all_linux
  displayName: Build all tasks (Linux)
  services:
    redis:
      image: redis
      ports:
      - 6379:6379
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.101'
  - script: cd scripts/aelf-node && bash start.sh
    displayName: 'Deploy a full node'
  - script: bash build.sh
    displayName: 'build and test'
- job: build_all_macos
# All tasks on macOS
  displayName: Build all tasks (macos)
  pool:
    vmImage: macos-latest
  variables:
    phpVersion: 7.2
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.101'
  - script: cd scripts/aelf-node && bash start-mac.sh
  - script: bash build.sh
    displayName: 'build and test'
